CREATE TABLE IF NOT EXISTS daily_missions (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    emoji VARCHAR(10) NOT NULL,
    mission_type VARCHAR(50) NOT NULL,
    target_value INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO daily_missions (title, emoji, mission_type, target_value) VALUES
-- exercises (40 misiones)
('Primer ejercicio', '📝', 'exercises', 1),
('Dos ejercicios', '✏️', 'exercises', 2),
('Tres ejercicios', '🖊️', 'exercises', 3),
('Cuatro ejercicios', '📄', 'exercises', 4),
('Cinco ejercicios', '🎯', 'exercises', 5),
('Seis ejercicios', '📐', 'exercises', 6),
('Siete ejercicios', '📏', 'exercises', 7),
('Ocho ejercicios', '🔢', 'exercises', 8),
('Nueve ejercicios', '➗', 'exercises', 9),
('Diez ejercicios', '🔟', 'exercises', 10),
('Doce ejercicios', '📊', 'exercises', 12),
('Catorce ejercicios', '📈', 'exercises', 14),
('Dieciséis ejercicios', '🧮', 'exercises', 16),
('Dieciocho ejercicios', '🔡', 'exercises', 18),
('Veinte ejercicios', '🏅', 'exercises', 20),
('Veintidós ejercicios', '🌟', 'exercises', 22),
('Veinticuatro ejercicios', '💡', 'exercises', 24),
('Veintiséis ejercicios', '🔭', 'exercises', 26),
('Veintiocho ejercicios', '⚡', 'exercises', 28),
('Treinta ejercicios', '🥇', 'exercises', 30),
('Treinta y dos', '🎖️', 'exercises', 32),
('Treinta y cuatro', '🏆', 'exercises', 34),
('Treinta y seis', '🎗️', 'exercises', 36),
('Treinta y ocho', '🔑', 'exercises', 38),
('Cuarenta ejercicios', '💎', 'exercises', 40),
('Cuarenta y cinco', '🌠', 'exercises', 45),
('Cincuenta ejercicios', '🚀', 'exercises', 50),
('Cincuenta y cinco', '🛸', 'exercises', 55),
('Sesenta ejercicios', '🌍', 'exercises', 60),
('Sesenta y cinco', '🔬', 'exercises', 65),
('Setenta ejercicios', '🧬', 'exercises', 70),
('Setenta y cinco', '⚗️', 'exercises', 75),
('Ochenta ejercicios', '🧪', 'exercises', 80),
('Ochenta y cinco', '🧲', 'exercises', 85),
('Noventa ejercicios', '🔋', 'exercises', 90),
('Noventa y cinco', '💻', 'exercises', 95),
('Cien ejercicios', '🎓', 'exercises', 100),
('Ciento diez ejercicios', '🏛️', 'exercises', 110),
('Ciento veinticinco ejercicios', '👑', 'exercises', 125),
('Ciento cincuenta ejercicios', '🌈', 'exercises', 150),

-- topics (20 misiones)
('Primer tema', '🗺️', 'topics', 1),
('Dos temas', '📚', 'topics', 2),
('Tres temas', '📖', 'topics', 3),
('Cuatro temas', '🔖', 'topics', 4),
('Cinco temas', '📕', 'topics', 5),
('Seis temas', '📗', 'topics', 6),
('Siete temas', '📘', 'topics', 7),
('Ocho temas', '📙', 'topics', 8),
('Nueve temas', '🗂️', 'topics', 9),
('Diez temas', '📂', 'topics', 10),
('Once temas', '🗃️', 'topics', 11),
('Doce temas', '🗄️', 'topics', 12),
('Trece temas', '📋', 'topics', 13),
('Catorce temas', '📑', 'topics', 14),
('Quince temas', '📃', 'topics', 15),
('Diecisiete temas', '🧭', 'topics', 17),
('Veinte temas', '🌐', 'topics', 20),
('Veintidós temas', '🔭', 'topics', 22),
('Veinticinco temas', '🏆', 'topics', 25),
('Treinta temas', '👑', 'topics', 30),

-- streak (20 misiones)
('Primer día', '🌅', 'streak', 1),
('Dos días seguidos', '🌤️', 'streak', 2),
('Tres días seguidos', '☀️', 'streak', 3),
('Cuatro días seguidos', '🌞', 'streak', 4),
('Cinco días seguidos', '🔥', 'streak', 5),
('Seis días seguidos', '💥', 'streak', 6),
('Una semana seguida', '🗓️', 'streak', 7),
('Ocho días seguidos', '⚡', 'streak', 8),
('Nueve días seguidos', '🌟', 'streak', 9),
('Diez días seguidos', '🎯', 'streak', 10),
('Once días seguidos', '💪', 'streak', 11),
('Doce días seguidos', '🏅', 'streak', 12),
('Trece días seguidos', '🎖️', 'streak', 13),
('Dos semanas seguidas', '📅', 'streak', 14),
('Quince días seguidos', '🏆', 'streak', 15),
('Veinte días seguidos', '🚀', 'streak', 20),
('Tres semanas seguidas', '🌈', 'streak', 21),
('Un mes seguido', '🎓', 'streak', 30),
('Dos meses seguidos', '👑', 'streak', 60),
('Tres meses seguidos', '🌠', 'streak', 90),

-- xp (20 misiones)
('Primeros 10 XP', '⭐', 'xp', 10),
('25 XP acumulados', '🌟', 'xp', 25),
('50 XP acumulados', '💫', 'xp', 50),
('75 XP acumulados', '✨', 'xp', 75),
('100 XP acumulados', '🥉', 'xp', 100),
('150 XP acumulados', '🥈', 'xp', 150),
('200 XP acumulados', '🥇', 'xp', 200),
('300 XP acumulados', '🏅', 'xp', 300),
('500 XP acumulados', '🎖️', 'xp', 500),
('750 XP acumulados', '🏆', 'xp', 750),
('1000 XP acumulados', '💎', 'xp', 1000),
('1500 XP acumulados', '💠', 'xp', 1500),
('2000 XP acumulados', '🔷', 'xp', 2000),
('3000 XP acumulados', '👑', 'xp', 3000),
('5000 XP acumulados', '🌈', 'xp', 5000),
('7500 XP acumulados', '🚀', 'xp', 7500),
('10000 XP acumulados', '🛸', 'xp', 10000),
('15000 XP acumulados', '🌍', 'xp', 15000),
('20000 XP acumulados', '🌠', 'xp', 20000),
('50000 XP acumulados', '🎓', 'xp', 50000);
